/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as DummyIndexRouteImport } from './routes/dummy/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AuthOrdersRouteImport } from './routes/_auth.orders'
import { Route as AuthCartRouteImport } from './routes/_auth.cart'
import { Route as AuthAdminRouteImport } from './routes/_auth.admin'
import { Route as DummyDemoTanstackQueryRouteImport } from './routes/dummy/demo.tanstack-query'
import { Route as DummyDemoFormSimpleRouteImport } from './routes/dummy/demo.form.simple'
import { Route as DummyDemoFormAddressRouteImport } from './routes/dummy/demo.form.address'

const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyIndexRoute = DummyIndexRouteImport.update({
  id: '/dummy/',
  path: '/dummy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOrdersRoute = AuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCartRoute = AuthCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const DummyDemoTanstackQueryRoute = DummyDemoTanstackQueryRouteImport.update({
  id: '/dummy/demo/tanstack-query',
  path: '/dummy/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyDemoFormSimpleRoute = DummyDemoFormSimpleRouteImport.update({
  id: '/dummy/demo/form/simple',
  path: '/dummy/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyDemoFormAddressRoute = DummyDemoFormAddressRouteImport.update({
  id: '/dummy/demo/form/address',
  path: '/dummy/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin': typeof AuthAdminRoute
  '/cart': typeof AuthCartRoute
  '/orders': typeof AuthOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/dummy': typeof DummyIndexRoute
  '/products': typeof ProductsIndexRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin': typeof AuthAdminRoute
  '/cart': typeof AuthCartRoute
  '/orders': typeof AuthOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/dummy': typeof DummyIndexRoute
  '/products': typeof ProductsIndexRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/_auth/admin': typeof AuthAdminRoute
  '/_auth/cart': typeof AuthCartRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/dummy/': typeof DummyIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/products/$slug'
    | '/dummy'
    | '/products'
    | '/dummy/demo/tanstack-query'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/products/$slug'
    | '/dummy'
    | '/products'
    | '/dummy/demo/tanstack-query'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/_auth/admin'
    | '/_auth/cart'
    | '/_auth/orders'
    | '/products/$slug'
    | '/dummy/'
    | '/products/'
    | '/dummy/demo/tanstack-query'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  DummyIndexRoute: typeof DummyIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DummyDemoTanstackQueryRoute: typeof DummyDemoTanstackQueryRoute
  DummyDemoFormAddressRoute: typeof DummyDemoFormAddressRoute
  DummyDemoFormSimpleRoute: typeof DummyDemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/': {
      id: '/dummy/'
      path: '/dummy'
      fullPath: '/dummy'
      preLoaderRoute: typeof DummyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cart': {
      id: '/_auth/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthCartRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/dummy/demo/tanstack-query': {
      id: '/dummy/demo/tanstack-query'
      path: '/dummy/demo/tanstack-query'
      fullPath: '/dummy/demo/tanstack-query'
      preLoaderRoute: typeof DummyDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/demo/form/simple': {
      id: '/dummy/demo/form/simple'
      path: '/dummy/demo/form/simple'
      fullPath: '/dummy/demo/form/simple'
      preLoaderRoute: typeof DummyDemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/demo/form/address': {
      id: '/dummy/demo/form/address'
      path: '/dummy/demo/form/address'
      fullPath: '/dummy/demo/form/address'
      preLoaderRoute: typeof DummyDemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRoute
  AuthCartRoute: typeof AuthCartRoute
  AuthOrdersRoute: typeof AuthOrdersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRoute,
  AuthCartRoute: AuthCartRoute,
  AuthOrdersRoute: AuthOrdersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  DummyIndexRoute: DummyIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DummyDemoTanstackQueryRoute: DummyDemoTanstackQueryRoute,
  DummyDemoFormAddressRoute: DummyDemoFormAddressRoute,
  DummyDemoFormSimpleRoute: DummyDemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
