/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as DummyIndexRouteImport } from './routes/dummy/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAuthRouteImport } from './routes/(main)/_auth'
import { Route as authVerifyRouteImport } from './routes/(auth)/verify'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as mainProductsIndexRouteImport } from './routes/(main)/products/index'
import { Route as DummyDemoTanstackQueryRouteImport } from './routes/dummy/demo.tanstack-query'
import { Route as mainProductsSlugRouteImport } from './routes/(main)/products/$slug'
import { Route as mainAuthOrdersRouteImport } from './routes/(main)/_auth.orders'
import { Route as mainAuthCartRouteImport } from './routes/(main)/_auth.cart'
import { Route as mainAuthAdminRouteImport } from './routes/(main)/_auth.admin'
import { Route as DummyDemoFormSimpleRouteImport } from './routes/dummy/demo.form.simple'
import { Route as DummyDemoFormAddressRouteImport } from './routes/dummy/demo.form.address'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyIndexRoute = DummyIndexRouteImport.update({
  id: '/dummy/',
  path: '/dummy/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthRoute = mainAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => mainRouteRoute,
} as any)
const authVerifyRoute = authVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const mainProductsIndexRoute = mainProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => mainRouteRoute,
} as any)
const DummyDemoTanstackQueryRoute = DummyDemoTanstackQueryRouteImport.update({
  id: '/dummy/demo/tanstack-query',
  path: '/dummy/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProductsSlugRoute = mainProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthOrdersRoute = mainAuthOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => mainAuthRoute,
} as any)
const mainAuthCartRoute = mainAuthCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => mainAuthRoute,
} as any)
const mainAuthAdminRoute = mainAuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => mainAuthRoute,
} as any)
const DummyDemoFormSimpleRoute = DummyDemoFormSimpleRouteImport.update({
  id: '/dummy/demo/form/simple',
  path: '/dummy/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DummyDemoFormAddressRoute = DummyDemoFormAddressRouteImport.update({
  id: '/dummy/demo/form/address',
  path: '/dummy/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify': typeof authVerifyRoute
  '/': typeof mainIndexRoute
  '/dummy': typeof DummyIndexRoute
  '/admin': typeof mainAuthAdminRoute
  '/cart': typeof mainAuthCartRoute
  '/orders': typeof mainAuthOrdersRoute
  '/products/$slug': typeof mainProductsSlugRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/products': typeof mainProductsIndexRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signup': typeof authSignupRoute
  '/verify': typeof authVerifyRoute
  '/': typeof mainIndexRoute
  '/dummy': typeof DummyIndexRoute
  '/admin': typeof mainAuthAdminRoute
  '/cart': typeof mainAuthCartRoute
  '/orders': typeof mainAuthOrdersRoute
  '/products/$slug': typeof mainProductsSlugRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/products': typeof mainProductsIndexRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify': typeof authVerifyRoute
  '/(main)/_auth': typeof mainAuthRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/dummy/': typeof DummyIndexRoute
  '/(main)/_auth/admin': typeof mainAuthAdminRoute
  '/(main)/_auth/cart': typeof mainAuthCartRoute
  '/(main)/_auth/orders': typeof mainAuthOrdersRoute
  '/(main)/products/$slug': typeof mainProductsSlugRoute
  '/dummy/demo/tanstack-query': typeof DummyDemoTanstackQueryRoute
  '/(main)/products/': typeof mainProductsIndexRoute
  '/dummy/demo/form/address': typeof DummyDemoFormAddressRoute
  '/dummy/demo/form/simple': typeof DummyDemoFormSimpleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/'
    | '/dummy'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/products/$slug'
    | '/dummy/demo/tanstack-query'
    | '/products'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/'
    | '/dummy'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/products/$slug'
    | '/dummy/demo/tanstack-query'
    | '/products'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  id:
    | '__root__'
    | '/(auth)'
    | '/(main)'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/(auth)/signup'
    | '/(auth)/verify'
    | '/(main)/_auth'
    | '/(main)/'
    | '/dummy/'
    | '/(main)/_auth/admin'
    | '/(main)/_auth/cart'
    | '/(main)/_auth/orders'
    | '/(main)/products/$slug'
    | '/dummy/demo/tanstack-query'
    | '/(main)/products/'
    | '/dummy/demo/form/address'
    | '/dummy/demo/form/simple'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  DummyIndexRoute: typeof DummyIndexRoute
  DummyDemoTanstackQueryRoute: typeof DummyDemoTanstackQueryRoute
  DummyDemoFormAddressRoute: typeof DummyDemoFormAddressRoute
  DummyDemoFormSimpleRoute: typeof DummyDemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/': {
      id: '/dummy/'
      path: '/dummy'
      fullPath: '/dummy'
      preLoaderRoute: typeof DummyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/_auth': {
      id: '/(main)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainAuthRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/verify': {
      id: '/(auth)/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(main)/products/': {
      id: '/(main)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof mainProductsIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/dummy/demo/tanstack-query': {
      id: '/dummy/demo/tanstack-query'
      path: '/dummy/demo/tanstack-query'
      fullPath: '/dummy/demo/tanstack-query'
      preLoaderRoute: typeof DummyDemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/products/$slug': {
      id: '/(main)/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof mainProductsSlugRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/_auth/orders': {
      id: '/(main)/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof mainAuthOrdersRouteImport
      parentRoute: typeof mainAuthRoute
    }
    '/(main)/_auth/cart': {
      id: '/(main)/_auth/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof mainAuthCartRouteImport
      parentRoute: typeof mainAuthRoute
    }
    '/(main)/_auth/admin': {
      id: '/(main)/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof mainAuthAdminRouteImport
      parentRoute: typeof mainAuthRoute
    }
    '/dummy/demo/form/simple': {
      id: '/dummy/demo/form/simple'
      path: '/dummy/demo/form/simple'
      fullPath: '/dummy/demo/form/simple'
      preLoaderRoute: typeof DummyDemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dummy/demo/form/address': {
      id: '/dummy/demo/form/address'
      path: '/dummy/demo/form/address'
      fullPath: '/dummy/demo/form/address'
      preLoaderRoute: typeof DummyDemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignupRoute: typeof authSignupRoute
  authVerifyRoute: typeof authVerifyRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignupRoute: authSignupRoute,
  authVerifyRoute: authVerifyRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainAuthRouteChildren {
  mainAuthAdminRoute: typeof mainAuthAdminRoute
  mainAuthCartRoute: typeof mainAuthCartRoute
  mainAuthOrdersRoute: typeof mainAuthOrdersRoute
}

const mainAuthRouteChildren: mainAuthRouteChildren = {
  mainAuthAdminRoute: mainAuthAdminRoute,
  mainAuthCartRoute: mainAuthCartRoute,
  mainAuthOrdersRoute: mainAuthOrdersRoute,
}

const mainAuthRouteWithChildren = mainAuthRoute._addFileChildren(
  mainAuthRouteChildren,
)

interface mainRouteRouteChildren {
  mainAuthRoute: typeof mainAuthRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
  mainProductsSlugRoute: typeof mainProductsSlugRoute
  mainProductsIndexRoute: typeof mainProductsIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAuthRoute: mainAuthRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
  mainProductsSlugRoute: mainProductsSlugRoute,
  mainProductsIndexRoute: mainProductsIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  DummyIndexRoute: DummyIndexRoute,
  DummyDemoTanstackQueryRoute: DummyDemoTanstackQueryRoute,
  DummyDemoFormAddressRoute: DummyDemoFormAddressRoute,
  DummyDemoFormSimpleRoute: DummyDemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
